  const activitiesByType = {
    housing: [
      { value: 100, label: "housing" },
      { value: 101, label: "apartment" },
      { value: 102, label: "loft" },
      { value: 103, label: "penthouse" },
      { value: 104, label: "villa" },
      { value: 105, label: "townHouse" },
      { value: 106, label: "duplex" },
      { value: 107, label: "twinVilla" },
      { value: 108, label: "roof" },
      { value: 109, label: "studio" },
    ],
    commercial: [
      { value: 200, label: "commercial" },
      { value: 201, label: "superMarket" },
      { value: 202, label: "pharmacy" },
      { value: 203, label: "bakery" },
      { value: 204, label: "vegetables" },
      { value: 205, label: "another" },
    ],
    industrial: [
      { value: 300, label: "industrial" },
      { value: 301, label: "buildingMaterials" },
      { value: 302, label: "autoIndustry" },
      { value: 303, label: "tobacco" },
      { value: 304, label: "leather" },
      { value: 305, label: "electronicIndustries" },
      { value: 306, label: "electrical" },
      { value: 307, label: "chemical" },
      { value: 308, label: "pharmaceutical" },
      { value: 309, label: "mechanical" },
      { value: 310, label: "deliveryServices" },
      { value: 311, label: "anotherActivity" },
      { value: 312, label: "without" },
    ],
    land: [
      { value: 400, label: "land" },
      { value: 401, label: "residential" },
      { value: 402, label: "commercial" },
      { value: 403, label: "administrative" },
      { value: 404, label: "entertaining" },
      { value: 405, label: "industrial" },
      { value: 406, label: "agricultural" },
      { value: 407, label: "store" },
      { value: 408, label: "medical" },
      { value: 409, label: "usufructRight" },
      { value: 410, label: "coastal" },
    ],
    coastal: [
      { value: 500, label: "coastal" },
      { value: 501, label: "chalet" },
      { value: 502, label: "apartment" },
      { value: 503, label: "loft" },
      { value: 504, label: "penthouse" },
      { value: 505, label: "villa" },
      { value: 506, label: "townHouse" },
      { value: 507, label: "duplex" },
      { value: 508, label: "twinVilla" },
      { value: 509, label: "roof" },
    ],
  };
  
  export default activitiesByType;
  